"""Initial migration with all tables

Revision ID: d146e5ef0e6b
Revises:
Create Date: 2025-11-17 05:17:51.080843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd146e5ef0e6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('schema_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_table_name'), 'datasets', ['table_name'], unique=True)
    op.create_index(op.f('ix_datasets_teacher_id'), 'datasets', ['teacher_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('custom_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('expected_query', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('hints_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('expected_output_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_challenges_dataset_id'), 'custom_challenges', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_custom_challenges_teacher_id'), 'custom_challenges', ['teacher_id'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('custom_challenge_id', sa.Integer(), nullable=True),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['custom_challenge_id'], ['custom_challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_challenge_id'), 'attempts', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_attempts_custom_challenge_id'), 'attempts', ['custom_challenge_id'], unique=False)
    op.create_index(op.f('ix_attempts_unit_id'), 'attempts', ['unit_id'], unique=False)
    op.create_index(op.f('ix_attempts_user_id'), 'attempts', ['user_id'], unique=False)
    op.create_table('hints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('custom_challenge_id', sa.Integer(), nullable=True),
    sa.Column('hint_level', sa.Integer(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['custom_challenge_id'], ['custom_challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hints_challenge_id'), 'hints', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_hints_custom_challenge_id'), 'hints', ['custom_challenge_id'], unique=False)
    op.create_index(op.f('ix_hints_unit_id'), 'hints', ['unit_id'], unique=False)
    op.create_index(op.f('ix_hints_user_id'), 'hints', ['user_id'], unique=False)
    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('custom_challenge_id', sa.Integer(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['custom_challenge_id'], ['custom_challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'unit_id', 'challenge_id', 'custom_challenge_id', name='unique_user_challenge')
    )
    op.create_index(op.f('ix_progress_challenge_id'), 'progress', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_progress_custom_challenge_id'), 'progress', ['custom_challenge_id'], unique=False)
    op.create_index(op.f('ix_progress_unit_id'), 'progress', ['unit_id'], unique=False)
    op.create_index(op.f('ix_progress_user_id'), 'progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_user_id'), table_name='progress')
    op.drop_index(op.f('ix_progress_unit_id'), table_name='progress')
    op.drop_index(op.f('ix_progress_custom_challenge_id'), table_name='progress')
    op.drop_index(op.f('ix_progress_challenge_id'), table_name='progress')
    op.drop_table('progress')
    op.drop_index(op.f('ix_hints_user_id'), table_name='hints')
    op.drop_index(op.f('ix_hints_unit_id'), table_name='hints')
    op.drop_index(op.f('ix_hints_custom_challenge_id'), table_name='hints')
    op.drop_index(op.f('ix_hints_challenge_id'), table_name='hints')
    op.drop_table('hints')
    op.drop_index(op.f('ix_attempts_user_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_unit_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_custom_challenge_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_challenge_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_custom_challenges_teacher_id'), table_name='custom_challenges')
    op.drop_index(op.f('ix_custom_challenges_dataset_id'), table_name='custom_challenges')
    op.drop_table('custom_challenges')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_datasets_teacher_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_table_name'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
